services:
  stirling-pdf-dev:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf-dev
    ports:
      - '4010:8080'
    volumes:
      - ./stirling-data:/configs
    restart: unless-stopped
